[params.profileMode]
enabled = true
title = "The Noobing Blog"
subtitle = "with NoobScience"

[[params.profileMode.buttons]]
name = "Archive"
url = "/archives"

[[params.profileMode.buttons]]
name = "Github"
url = "https://github.com/newtoallofthis123/Noobing"

[[params.socialIcons]]
name = "Website"
url = "https://newtoallofthis123.github.io/About"

[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/noobscience1"

[[params.socialIcons]]
name = "Instagram"
url = "https://instagram.com/noobscience123"

[[params.socialIcons]]
name = "github"
url = "https://github.com/newtoallofthis123"

[[params.socialIcons]]
name = "YouTube"
url = "https://www.youtube.com/channel/UCbYWy7rhUhToM3tbw-Z3SnQ"

[[params.socialIcons]]
name = "email"
url = "mailto:noobscience123@gmail.com"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[params]
ShowShareButtons = true
ShowReadingTime = true
ShowToc = true
TocOpen = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
description = "NoobScience's Blog"

[menu]
[[menu.main]]
identifier = "search"
name = "Search"
pre = "<i class='bi bi-search' style='padding-right: 5px;'></i>"
url = "/search"
weight = 10

[[menu.main]]
identifier = "Archive"
name = "Archive"
pre = "<i class='bi bi-archive' style='padding-right: 5px;'></i>"
url = "/archives"
weight = 20

[[menu.main]]
identifier = "RSS"
name = "RSS"
pre = "<i class='bi bi-rss' style='padding-right: 5px;'></i>"
url = "/index.xml"
weight = 30

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
style = "monokai"